container:
  image: power-lines-fixture-service
  resourceTier: M
  port: 5002
  comPlusEnableDiagnostics: 0

configMap:
  environment: production
  analysisEndpoint: http://power-lines-analysis-service

message:
  host: services.lynxmagnus.com
  port: 5672
  fixtureQueue: power-lines-fixtures
  fixtureSubscription: power-lines-fixtures-fixture
  analysisQueue: power-lines-analysis
  oddsQueue: power-lines-odds
  oddsSubscription: power-lines-odds-fixture

deployment: {}

secret:
  secretsPath: /power-lines-fixture-service
