environment: production
name: power-lines-fixture-service
image: power-lines-fixture-service

container:
  requestMemory: 60Mi
  requestCpu: 60m
  limitMemory: 250Mi
  limitCpu: 250m
  port: 5002
  comPlusEnableDiagnostics: 0
  connectionString: "User Id=postgres;Password=postgres;Server=power-lines-fixture-service-postgres;Port=5432;Database=Database=power_lines_fixture;"
  analysisEndpoint: http://power-lines-analysis-service

message:
  host: host.docker.internal
  port: 5672
  username: rabbitmq
  password: rabbitmq
  fixtureQueue: power-lines-fixtures
  fixtureSubscription: power-lines-fixtures-fixture
  analysisQueue: power-lines-analysis
  oddsQueue: power-lines-odds
  oddsSubscription: power-lines-odds-fixture

deployment: {}
