version: '3.7'
services:
  power-lines-fixture-service:
    build:
      target: development
    depends_on: 
      - power-lines-message
      - power-lines-fixture-service-postgres
    entrypoint: >
      sh -c "
        scripts/wait-for.sh power-lines-message:6000 --
        scripts/wait-for.sh power-lines-fixture-service-postgres:5432 --
        dotnet watch --project ./PowerLinesFixtureService run --urls "http://*:5000""
    ports:
      - "5000:5000"
    environment:
      ConnectionStrings__PowerLinesFixtureService: "Server=power-lines-fixture-service-postgres;Port=5432;Database=power_lines_fixtures;User Id=postgres;Password=postgres;"
      Message__Host: power-lines-message
      AnalysisUrl__Endpoint: http://power-lines-analysis-service:5001
    volumes:
      - ./PowerLinesFixtureService:/home/dotnet/PowerLinesFixtureService
      - ./PowerLinesFixtureService.Tests:/home/dotnet/PowerLinesFixtureService.Tests
      - ./scripts:/home/dotnet/scripts

  power-lines-message:
    image: rabbitmq:3-management-alpine
    container_name: power-lines-message
    hostname: power-lines-message
    environment:
      RABBITMQ_ERLANG_COOKIE: rabbitmq
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"

  power-lines-fixture-service-postgres:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_DB: power_lines_fixtures
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6000:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: {}
