version: '3.7'
services:
  power-lines-fixture-service-diet:
    build:
      context: .
      target: production-env
    image: power-lines-fixture-service
    container_name: power-lines-fixture-service
    ports:
      - "8000:80"
    environment:
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
