version: '3.7'
services:
  power-lines-fixture-service:
    build: 
      context: .
      target: development-env
    ports:
      - "5000:5000"
      - "5001:5001"      
    volumes:
      - ./PowerLinesFixtureService:/PowerLinesFixtureService

volumes:
  postgres_data: {}

networks:
  default:
    external:
      name: power-lines
