{{- define "power-lines-fixture-service.container" -}}
envFrom:
- configMapRef:
    name: {{ .Values.name }}
- secretRef:
    name: {{ .Values.name }}
ports:
- containerPort: {{ .Values.container.port }}
  name: http
  protocol: TCP
{{- end -}}
